Add fittable
MinishLab/model2vec pull request #140
Opened 2024-12-23 13:31 UTC by stephantul

2025-01-04 16:39 UTC, Pringled requested changes
Looks good! Some minor comments and suggestions.

2025-01-04 16:39 UTC, Pringled commented on model2vec/train/classifier.py
> +    def fit(
This function is quite long and complex, I think it would be better/more readable to split this into smaller parts, but up to you

2025-01-04 16:39 UTC, Pringled commented on model2vec/train/base.py
> +        return self.head(encoded), encoded
Is the second tensor (encoded) actually used anywhere in the code?

2025-01-04 16:39 UTC, Pringled commented on pyproject.toml
> +train = ["torch", "lightning"]
I think it's a bit safer to pin these (at least softpin) as torch and lightning tend to have breaking major releases, but we are also not doing that in distill, wdyt? Maybe just < 3 would make sense

2025-01-04 16:39 UTC, Pringled commented on model2vec/train/classifier.py
> +    ) -> None:
Imo learning rate should also be a changeable parameter

2025-01-04 16:39 UTC, Pringled commented on model2vec/train/classifier.py
> +                X, y, test_size=0.1, random_state=42, shuffle=True
Should we allow for more control over train/test splitting (e.g. train/test/val splits, setting the sizes, etc), or is that something users can edit themselves here if desired?

2025-01-04 16:39 UTC, Pringled commented on model2vec/train/classifier.py
> +        batch_size = 32
Would make this a default param

2025-01-05 19:45 UTC, Pringled approved these changes

2025-01-26 09:27 UTC, davidberenstein1957 reviewed
Looks super useful. left some comments. Also, perhaps we can add some reference to multi-label usage somewhere?

2025-01-26 09:27 UTC, davidberenstein1957 commented on model2vec/inference/model.py
> +    def push_to_hub(self, repo_id: str, token: str | None = None, private: bool = False) -> None:
I would add a modelcard and perhaps tags or a library reference, this helps a lot with visibility, usability and findability.

https://huggingface.co/docs/hub/model-cards#specifying-a-library

2025-01-26 09:27 UTC, davidberenstein1957 commented on model2vec/inference/model.py
> +    def from_pretrained(
can't we load it from the Hub? perhaps we should align the arguments a bit with the `transformers` naming given you've also adopted `from_pretrained`? 

For example using `pretrained_model_name_or_path`. https://huggingface.co/docs/transformers/v4.48.0/en/model_doc/auto#transformers.AutoTokenizer.from_pretrained

2025-01-26 09:27 UTC, davidberenstein1957 commented on model2vec/inference/model.py
> +        return self.head.predict_proba(encoded)
Maybe we can also add a `__call__`?

2025-01-26 09:27 UTC, davidberenstein1957 commented on model2vec/model.py
Perhaps we can add `get_sentence_embedding_dimension()` like sentence transformers?

2025-01-26 09:27 UTC, davidberenstein1957 commented on model2vec/train/README.md
> +Aside from [distillation](../../README.md#distillation), `model2vec` also supports training simple classifiers on top of static models, using [pytorch](https://pytorch.org/) and [lightning](https://l
And sklearn right?

2025-01-26 09:27 UTC, davidberenstein1957 commented on model2vec/train/classifier.py
> +    def to_pipeline(self) -> StaticModelPipeline:
Should we be mre epxlicit and convert call this `to_sklearn_pipeline`?

2025-01-26 09:27 UTC, davidberenstein1957 commented on model2vec/train/classifier.py
> +        return np.concatenate(pred)
Do we want a `__call__` too?

2025-01-26 09:27 UTC, davidberenstein1957 commented on model2vec/train/README.md
> +This pipeline object can be persisted using standard pickle-based methods, such as [joblib](https://joblib.readthedocs.io/en/stable/). This makes it easy to use your model in inferene pipelines (no i
I believe there are some security concerns with pickle and joblib https://calmcode.io/course/scikit-save/security.

2025-01-26 09:27 UTC, davidberenstein1957 commented on model2vec/train/README.md
> +| dataset name               |   logistic regression head   |  full finetune |
Perhaps show how it compares to setfit, it being a direct competitor?

2025-01-26 09:27 UTC, davidberenstein1957 commented on model2vec/train/classifier.py
> +            modules.extend([nn.Linear(self.hidden_dim, self.hidden_dim), nn.ReLU()])
```suggestion
            modules.extend([nn.Linear(self.hidden_dim, self.hidden_dim), nn.ReLU()] * (self.n_layers - 1))
```

2025-01-26 09:27 UTC, davidberenstein1957 commented on model2vec/train/classifier.py
> +        pl.seed_everything(42)
Don't we want to be able to pass a seed?

2025-01-26 09:27 UTC, davidberenstein1957 commented on model2vec/train/classifier.py
> +        with TemporaryDirectory() as tempdir:
This is to not create a random training directory when fitting?

2025-01-26 09:27 UTC, davidberenstein1957 commented on model2vec/train/classifier.py
> +        random_state = np.random.RandomState(42)
same w.r.t. random seed. If we don't want users to be able to define this. Perhaps we could create `RANDOM_SEED` somewhere and re-use it instead of copy-pasting 42?

2025-01-26 12:08 UTC, stephantul commented on model2vec/model.py
>              self.normalize = self.config.get("normalize", False)
This is intentional. `normalize` checks whether the value had been set before in the config and warns the user if it was something other than the provided value. assigning to `self._normalize` just sets it directly.

2025-01-26 12:08 UTC, stephantul commented on model2vec/model.py
>              self.normalize = self.config.get("normalize", False)
I do think we could change the setter to fix this.

2025-01-26 12:09 UTC, stephantul commented on model2vec/inference/model.py
> +    def push_to_hub(self, repo_id: str, token: str | None = None, private: bool = False) -> None:
This actually already happens because we push the underlying static model to the hub, which has a model card. This model card template is specified in the root of the code.

2025-01-26 12:11 UTC, stephantul commented on model2vec/inference/model.py
> +    def from_pretrained(
from_pretrained loads from the hub. The arguments mimic the ones from `StaticModel` and, although they don't match transformers exactly, we're wary of introducing breaking changes.

2025-01-26 12:12 UTC, stephantul commented on model2vec/model.py
this is already in here, it's called `dim`. It's a property, not a function.

2025-01-26 12:12 UTC, stephantul commented on model2vec/train/README.md
> +Aside from [distillation](../../README.md#distillation), `model2vec` also supports training simple classifiers on top of static models, using [pytorch](https://pytorch.org/) and [lightning](https://l
Good catch!

2025-01-26 12:13 UTC, stephantul commented on model2vec/train/classifier.py
> +    def to_pipeline(self) -> StaticModelPipeline:
I thought of this, but it's actually not an sklearn pipeline (as in `sklearn.pipeline.Pipeline`). Maybe `to_staticmodelpipeline`?

2025-01-26 12:14 UTC, stephantul commented on model2vec/train/README.md
> +This pipeline object can be persisted using standard pickle-based methods, such as [joblib](https://joblib.readthedocs.io/en/stable/). This makes it easy to use your model in inferene pipelines (no i
We load using `skops` internally, so pushing to the hub and so on is safe if you use this library. But yeah I'll add a note to this effect.

2025-01-26 12:15 UTC, stephantul commented on model2vec/train/classifier.py
> +        with TemporaryDirectory() as tempdir:
yep! We do need a training directory to be able to load the best checkpoint.

2025-02-07 10:34 UTC, Pringled requested changes
Couple of comments and suggestions

2025-02-07 10:34 UTC, Pringled commented on model2vec/inference/README.md
> +Let's assume you're using our `potion-edu classifier`.
```suggestion
Let's assume you're using our [potion-edu classifier](https://huggingface.co/minishlab/potion-8m-edu-classifier).
```

2025-02-07 10:34 UTC, Pringled commented on model2vec/inference/README.md
> +s = StaticModelPipeline.from_pretrained("minishlab/potion-8m-edu-classifier")
```suggestion
classifier = StaticModelPipeline.from_pretrained("minishlab/potion-8m-edu-classifier")
```

2025-02-07 10:34 UTC, Pringled commented on model2vec/inference/README.md
> +label = s.predict("Attitudes towards cattle in the Alps: a study in letting go.")
```suggestion
label = classifier.predict("Attitudes towards cattle in the Alps: a study in letting go.")
```

2025-02-07 10:34 UTC, Pringled commented on model2vec/inference/model.py
> +        cls: type[StaticModelPipeline], path: PathLike, token: str | None = None
Should also accept trust_remote_code, and pass it to _load_pipeline I think

2025-02-07 10:34 UTC, Pringled commented on model2vec/inference/model.py
> +        encoded = self.model.encode(X)
There's no control over encode since this is in a private function, I'm not sure if we want to give any control here? E.g batch size, multiprocessing, etc?

2025-02-07 10:34 UTC, Pringled commented on model2vec/train/classifier.py
> +        optimizer = torch.optim.Adam(self.model.parameters(), lr=1e-3)
I think learning rate is now ignored, this should be:
```suggestion
        optimizer = torch.optim.Adam(self.model.parameters(), lr=self.learning_rate)
```

2025-02-07 10:34 UTC, Pringled commented on tutorials/train_classifier.ipynb
> +{
This prints in the notebook are not saved/pushed I think. This is a bit weird, for example when you have:
"Pretty good! We outperform the tf-idf pipeline by a wide margin.", it doesn't actually show it in the notebook (see https://github.com/MinishLab/model2vec/blob/add-fittable/tutorials/train_classifier.ipynb).

2025-02-07 19:33 UTC, Pringled approved these changes
:heart_eyes:

2025-02-07 19:34 UTC, merged